/**
 * @license
 * Copyright 2012 Mozilla Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @fileoverview
 *
 * Public entry point of the FontManager sub-system.  Both TypeScript and
 * JavaScript consumers should import from this module:
 *
 * ```ts
 * import { FontManager, createLegacyCMapFetcher } from
 *   "../shared/font_manager/index.ts";
 * ```
 *
 * The compiled output (`index.js` + `index.d.ts`) is generated by the
 * dedicated `tsconfig.font-manager.json` configuration and is safe to import
 * from the existing JavaScript codebase.
 */

export { FontManager } from "./font_manager.ts";
export type { ResolveFontResult } from "./font_manager.ts";
export { EventBus } from "./event_bus.ts";
export type { EventListener } from "./event_bus.ts";
export { FontCache } from "./font_cache.ts";
export type {
  EvictionListener,
  EvictionNotification,
} from "./font_cache.ts";
export { CMapLoader } from "./cmap_loader.ts";
export type { CMapLoaderDependencies } from "./cmap_loader.ts";
export { StandardFontLoader } from "./standard_font_loader.ts";
export type { StandardFontLoaderDependencies } from "./standard_font_loader.ts";
export { FontFallbackChain, toFontName } from "./fallback_chain.ts";
export type {
  FontAvailabilityChecker,
  FallbackContext,
  SubstitutionRule,
} from "./fallback_chain.ts";
export {
  createBinaryFetcherFromFactory,
  createLegacyCMapFetcher,
  createLegacyStandardFontFetcher,
  registerLegacyFont,
  toFontDescriptor,
} from "./adapters.ts";
export {
  asCMapName,
  asFontName,
  cacheKey,
  COMMON_CMAP_NAMES,
  DEFAULT_CACHE_OPTIONS,
  DEFAULT_PRELOAD_STRATEGY,
} from "./types.ts";
export type {
  BinaryFetcher,
  CSSFontInfo,
  CacheEntryStats,
  CacheKey,
  CacheOptions,
  CacheStats,
  CMapData,
  CMapName,
  CMapUrl,
  EvictionPolicy,
  FallbackEntry,
  FallbackReason,
  FallbackStrategyName,
  FontDescriptor,
  FontManagerEventMap,
  FontManagerEventName,
  FontManagerOptions,
  FontName,
  PreloadStrategy,
  ResourceKind,
  ResourceRequest,
  StandardFontDataUrl,
} from "./types.ts";
